<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class FurniturDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('furnitur_details')->insert([
            [
                'furnitur_id' => 1,
                'full_description' => "Tempat Tidur Minimalis dengan desain modern yang elegan, terbuat dari kayu berkualitas tinggi yang tahan lama dan nyaman untuk istirahat Anda.",
                'material' => 'Kayu Mahoni',
                'dimensi' => '200cm x 160cm x 40cm',
                'berat' => 40,
                'warna' => 'Coklat Muda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'furnitur_id' => 2,
                'full_description' => "Nakas Minimalis dengan desain simple dan fungsional, dilengkapi dengan dua laci untuk menyimpan barang-barang kecil Anda dengan rapi.",
                'material' => 'Kayu Jati',
                'dimensi' => '50cm x 40cm x 60cm',
                'berat' => 15,
                'warna' => 'Coklat Tua',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'furnitur_id' => 3,
                'full_description' => "Meja Belajar Jepang yang ergonomis dengan ruang penyimpanan praktis, cocok untuk menciptakan suasana belajar yang nyaman.",
                'material' => 'Kayu Pinus',
                'dimensi' => '120cm x 60cm x 75cm',
                'berat' => 25,
                'warna' => 'Natural Wood',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'furnitur_id' => 4,
                'full_description' => "Buffet Industri dengan perpaduan besi dan kayu reklamasi yang kokoh dan stylish, ideal untuk ruang dengan tema industrial.",
                'material' => 'Besi dan Kayu Reklamasi',
                'dimensi' => '150cm x 45cm x 80cm',
                'berat' => 55,
                'warna' => 'Hitam dan Coklat',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'furnitur_id' => 5,
                'full_description' => "Nakas Klasik dengan desain tradisional, memberikan sentuhan elegan dan kehangatan di kamar tidur Anda.",
                'material' => 'Kayu Mahoni',
                'dimensi' => '55cm x 45cm x 65cm',
                'berat' => 18,
                'warna' => 'Coklat Gelap',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'furnitur_id' => 6,
                'full_description' => "Rak Klasik yang kuat dan tahan lama, cocok untuk menyimpan buku dan barang dekorasi dengan gaya elegan.",
                'material' => 'Kayu Mahoni',
                'dimensi' => '180cm x 60cm x 30cm',
                'berat' => 30,
                'warna' => 'Coklat Tua',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'furnitur_id' => 7,
                'full_description' => "Kabinet Modern dengan desain minimalis dan fungsional, memberikan solusi penyimpanan yang praktis dan estetis.",
                'material' => 'Kayu MDF',
                'dimensi' => '120cm x 40cm x 80cm',
                'berat' => 25,
                'warna' => 'Putih',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'furnitur_id' => 8,
                'full_description' => "Kursi Makan Scandinavian dengan desain simpel dan nyaman, cocok untuk ruang makan modern.",
                'material' => 'Kayu Pinus dan Kain',
                'dimensi' => '45cm x 45cm x 90cm',
                'berat' => 7,
                'warna' => 'Putih dan Abu-abu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'furnitur_id' => 9,
                'full_description' => "Meja Kopi Minimalis dengan permukaan kaca tempered dan rangka besi hitam, menambah kesan modern di ruang tamu Anda.",
                'material' => 'Kaca Tempered dan Besi',
                'dimensi' => '90cm x 45cm x 40cm',
                'berat' => 12,
                'warna' => 'Hitam dan Transparan',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'furnitur_id' => 10,
                'full_description' => "Sofa L bentuk dengan bahan kain berkualitas tinggi dan bantalan empuk untuk kenyamanan maksimal.",
                'material' => 'Kain Poliester',
                'dimensi' => '220cm x 150cm x 85cm',
                'berat' => 70,
                'warna' => 'Abu-abu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'furnitur_id' => 11,
                'full_description' => "Meja Makan Kayu Solid dengan desain klasik dan tahan lama, cocok untuk keluarga besar.",
                'material' => 'Kayu Jati',
                'dimensi' => '200cm x 100cm x 75cm',
                'berat' => 80,
                'warna' => 'Coklat Tua',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'furnitur_id' => 12,
                'full_description' => "Lemari Pakaian Minimalis dengan pintu geser, memberikan solusi penyimpanan yang efisien di kamar Anda.",
                'material' => 'Kayu MDF',
                'dimensi' => '180cm x 60cm x 220cm',
                'berat' => 90,
                'warna' => 'Putih',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'furnitur_id' => 13,
                'full_description' => "Meja Konsol dengan desain elegan dan permukaan kayu solid, cocok untuk ruang tamu atau lorong rumah Anda.",
                'material' => 'Kayu Mahoni',
                'dimensi' => '120cm x 35cm x 75cm',
                'berat' => 22,
                'warna' => 'Coklat Muda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'furnitur_id' => 14,
                'full_description' => "Rak Sepatu Minimalis dengan bahan kayu dan finishing halus, menyimpan sepatu dengan rapi.",
                'material' => 'Kayu Pinus',
                'dimensi' => '80cm x 30cm x 100cm',
                'berat' => 15,
                'warna' => 'Natural Wood',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'furnitur_id' => 15,
                'full_description' => "Kursi Kerja Ergonomis dengan sandaran punggung dan bantalan empuk, memberikan kenyamanan saat bekerja.",
                'material' => 'Kain Poliester dan Besi',
                'dimensi' => '60cm x 60cm x 110cm',
                'berat' => 12,
                'warna' => 'Hitam',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'furnitur_id' => 16,
                'full_description' => "Meja Rias dengan cermin besar dan laci penyimpanan, membantu Anda menata kosmetik dengan rapi.",
                'material' => 'Kayu MDF',
                'dimensi' => '100cm x 45cm x 75cm',
                'berat' => 28,
                'warna' => 'Putih',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'furnitur_id' => 17,
                'full_description' => "Tempat Tidur Susun untuk anak dengan desain aman dan tahan lama, ideal untuk kamar tidur kecil.",
                'material' => 'Kayu Pinus',
                'dimensi' => '200cm x 90cm x 150cm',
                'berat' => 50,
                'warna' => 'Coklat Muda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'furnitur_id' => 18,
                'full_description' => "Meja Tulis Minimalis dengan permukaan luas dan desain simpel, cocok untuk ruang kerja atau belajar.",
                'material' => 'Kayu MDF',
                'dimensi' => '140cm x 60cm x 75cm',
                'berat' => 25,
                'warna' => 'Putih',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
